name: Initialise TF backend

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/initialise-backend/**'

jobs:
    tf_unit_test:
        name: Terraform unit testing
        runs-on: ubuntu-latest
        steps:

            - name: Checkout repo
              uses: actions/checkout@v3
 
            - uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 0.15.3

            - name: Terraform fmt
              id: fmt
              run: terraform fmt -recursive -check
              working-directory: initialise-backend

            - name: Terraform validate
              id: validate
              run: terraform validate
              working-directory: initialise-backend
